### ISSUE TITLE
Scope Tickets page updates

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/2016.Mozillafestival.org#5]
Link to current page: https://2015.mozillafestival.org/tickets

**What needs updating by June:** 
- [ ]  Update link
- [ ]  Provide more information about tickets on this page
- [x] Make page look spiffy

**Other thoughts/ideas**:
- [ ]

**Comment by vazquez** [comment]
Tito page has been spiffied up –
GH Issue: https://github.com/mozilla/mozillafestival.org/issues/364 
Tito Page: https://ti.to/Mozilla/mozfest-2016

**Comment by edrushka** [comment]
Very nice!!

@sallen, flagging we need to write any addition copy we want on this page. Also, will we have only 2 categories of tickets again this year?

**Comment by edrushka** [comment]
@Saallen what are the categories of tickets we'll have this year?

**Comment by Saallen** [comment]
Hi @vazquez 
Did you see last years ticket page? https://2015.mozillafestival.org/tickets
@edrushka On the website we will only have two types of tickets- Adult and Youth, I will work on the copy now for the website page

**Comment by edrushka** [comment]
@Saallen have you finished that copy?

**Comment by Saallen** [comment]
It is on todo for tomorrow 🐑 ish

**Comment by Saallen** [comment]
Youth ticket copy - Join us for three days to build, debate and explore our lives online. This ticket covers entry, lunch, swag and two days of building, making and learning on Saturday 29th and Sunday 30th of October. This ticket is for those under the age of 18. If the ticket holder is under 16 years of age they must be accompanied by an adult or part of a school group

**Comment by Saallen** [comment]
Adult ticket copy - Join us for three days to build, debate and explore our lives online. This ticket gains you entry to the festival from Friday night at 18:00 for the Science Fair and two days of sessions, workshops and talks taking place all day Saturday and Sunday. This ticket will also cover great coffee, lunch on Saturday, Sunday and adult beverages! Plus swag, an after party, demos and so much other great stuff that we cannot fit here

**Comment by Saallen** [comment]
Main copy cc @edrushka - it might be too much but.... 🐹 
MozFest is a 3 day extavaga of  participant-led sessions, inspiring talks, hands on workshops, digital art galleries, VR games, web literacy training, raspberry pi hacks, hall way conversations, youth lead learning labs, diversity training love fest for the open web.
MozFest is populated with people that are open, friendly and eager to help. Participants of all ages and skill levels are welcome. 

To get the most from the festival we encourage you to attend full days, so that means come meet  the people, organisations and companies attending on Friday night,   joining us before 9:00 on Saturday morning for keynotes and call to actions for the weekend, and being present on Sunday morning to participate in building, making and peer to peer workshops. 
We have a schedule of events, timings and session which we will release in October but check out "what to expect" in the meantime so you know what the weekend will fully entail.
If you are an educator or teacher bring young people to the event, please email us at festival@mozilla.org before you buy tickets as we can help with group discounts.
If you are a parent with young children we have a free creche onsite open Saturday and Sunday so bring the whole family. If you want to give us feedback, be more involved or ask questions email us at festival@mozilla.org

But mainly, join us, buy a ticket and help us fight to keep the web open and free

**Comment by edrushka** [comment]
@Saallen I'm going to edit the ticket types for consistency because it currently seems like there are different offerings for youth and adults ('two days of building, making and learning' vs 'two days of sessions, workshops and talks').

Also, let's discuss adding main copy to this page. This isn't in scope for June 1, as Ricardo won't be available to create and style a new section (there isn't currently a place for this copy).

**Comment by edrushka** [comment]
@vazquez @ScottDowne here is the copy to go under the youth and adult ticket icons on the Tickets page.

**Description for youth ticket:**
This ticket covers entry to the festival on Saturday and Sunday. It includes lunch, beverages, swag, and two days of building, making and learning. Youth tickets are for those under 18. Youth under 16 must be accompanied by an adult. If you are an educator bringing young people to the event, please email us at festival@mozilla.org before you buy tickets as we can help with group discounts.

**Description for adult ticket:**
This ticket covers entry to the festival on Friday night, Saturday and Sunday. It includes lunch, coffee, adult beverages, swag, and two days of building, making and learning (plus a party on Saturday evening!) If you are a parent with young children, we have a free creche onsite open Saturday and Sunday.
