### ISSUE TITLE
Changing label colours

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/2016.Mozillafestival.org#66]
Hello @mmmavis 
Are you gravy with me changing the colours of the space labels?
Currently they are all the same colour and this is confusing some wranglers?

Also I noticed that ppl are asking about travel stipend requests being highlighted.
Is there a way later in AUg to tag the issues that request travel assistance as per their response to the call form?
cc @edrushka

**Comment by mmmavis** [comment]
@Saallen 

> Are you gravy with me changing the colours of the space labels?
> Currently they are all the same colour and this is confusing some wranglers?

Yup feel free to change the colours! Just make sure that the label text stay unchanged! 👌

**Comment by mmmavis** [comment]
@Saallen 

> Also I noticed that ppl are asking about travel stipend requests being highlighted.
> Is there a way later in AUg to tag the issues that request travel assistance as per their response to the call form?

I'd suggest changing the exporting script soon so that travel stipend is highlighted for **future** proposal submissions. Since we only have ~40 submitted proposals now, I can manually update them on the program repo (we should tackle this early before the number grows 👀). How do you wanna highlight those proposals? Include a meta to the ticket description? Apply a specific label? Or?

**Comment by Saallen** [comment]
I think having a label for those requesting stipends
So those with the response travel-only get a label called  " Stipend requested"

Thanks @mmmavis I should of had spotted this earlier

**Comment by mmmavis** [comment]
`Stipend requested` label has been added. Sample ticket looks like this: https://github.com/MozillaFoundation/mozfest-program-2016/issues/52 (feel free to change the colour of the label 😉 )

**Comment by mmmavis** [comment]
DONE 👯 👯 👯 👯 👯

**Comment by Saallen** [comment]
Whoop 🌈 thanks !
