### ISSUE TITLE
Change URL for submission form

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/2016.Mozillafestival.org#74]
Once the call for proposals closes, we need a non-public way for space wranglers and staff to add last minute submissions.

Can you change the URL of the form? https://mozillafestival.org/proposals

Call for Proposals closes end of day August 1.

cc @mmmavis @Saallen

**Comment by alanmoo** [comment]
The irony being that since we're on github, technically there is no non-public way to hide it 😁

**Comment by Saallen** [comment]
Wide open!
We just want to close the open Call on time but always have a few last
minute requests via email.
It is always easier to add via a form rather than directly to github than
mess it's mojo.

I will close the other language forms and the additional mozex at 9pm UTc.
560 submissions so far and counting....fingers crossed for 600

**Comment by alanmoo** [comment]
This is on staging. New route will be `/late-proposals`

(I'll deploy it to production at 21:00UTC)

**Comment by edrushka** [comment]
👍 🙇
